id: HPEArubaClearpass_TestPlaybook-736a-4239-84e9-1f52a93a510f
version: -1
name: HPEArubaClearpass_TestPlaybook
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 1aec6123-ae63-45e9-83b1-4f4d7abad774
    type: start
    task:
      id: 1aec6123-ae63-45e9-83b1-4f4d7abad774
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: b07a73f8-2aa5-4279-843c-b41f87d2388f
    type: regular
    task:
      id: b07a73f8-2aa5-4279-843c-b41f87d2388f
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
      - "15"
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: e26c4cde-4c5c-4954-8c56-1d96f6e623fe
    type: regular
    task:
      id: e26c4cde-4c5c-4954-8c56-1d96f6e623fe
      version: -1
      name: Get endpoints list
      description: Get a list of endpoints.
      script: '|||aruba-clearpass-endpoints-list'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 7ce126db-f703-4da6-8783-83dd350a11d2
    type: condition
    task:
      id: 7ce126db-f703-4da6-8783-83dd350a11d2
      version: -1
      name: Verify endpoints list
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "5"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: HPEArubaClearpass.endpoints.list.[0]
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: e84612a3-0478-411a-818c-3964612442f2
    type: title
    task:
      id: e84612a3-0478-411a-818c-3964612442f2
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1595
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: fd196634-7bb7-4bb0-8053-75069115c282
    type: regular
    task:
      id: fd196634-7bb7-4bb0-8053-75069115c282
      version: -1
      name: Update endpoint description
      description: Updates some fields of an endpoint.
      script: '|||aruba-clearpass-endpoint-update'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      description:
        simple: test_playbook
      endpoint_id:
        simple: ${HPEArubaClearpass.endpoints.list.[0].id}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: 64e32ce8-01b5-4837-83a7-7f5e11345d2b
    type: condition
    task:
      id: 64e32ce8-01b5-4837-83a7-7f5e11345d2b
      version: -1
      name: Verify description update
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: HPEArubaClearpass.endpoints.update.Description
            iscontext: true
          right:
            value:
              simple: test_playbook
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: a9e507a0-732c-4112-84a8-797c3ffda762
    type: condition
    task:
      id: a9e507a0-732c-4112-84a8-797c3ffda762
      version: -1
      name: Verify attributes list
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "11"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: in
          left:
            value:
              simple: ${HPEArubaClearpass.attributes.create.ID}
            iscontext: true
          right:
            value:
              simple: ${HPEArubaClearpass.attributes.list.id}
    view: |-
      {
        "position": {
          "x": 592.5,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: 706133af-9120-46dd-869f-1402134f1354
    type: regular
    task:
      id: 706133af-9120-46dd-869f-1402134f1354
      version: -1
      name: Create new attribute
      description: Create a new attribute.
      script: '|||aruba-clearpass-attribute-create'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      data_type:
        simple: String
      entity_name:
        simple: Device
      name:
        simple: ${RandomString}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 592.5,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: effc71fb-7e19-4d3d-8d9f-97a0b99af35c
    type: regular
    task:
      id: effc71fb-7e19-4d3d-8d9f-97a0b99af35c
      version: -1
      name: Get attribute
      description: Get a list of attributes. If no arguments were given, all of the
        attributes will be displayed.
      script: '|||aruba-clearpass-attributes-list'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      attribute_id:
        complex:
          root: HPEArubaClearpass.attributes.create
          accessor: ID
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 592.5,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "11":
    id: "11"
    taskid: ba6c521e-36b2-421b-8ee7-45c88852fcca
    type: regular
    task:
      id: ba6c521e-36b2-421b-8ee7-45c88852fcca
      version: -1
      name: Update attribute fields
      description: Update some fields of an attribute by the attribute's ID.
      script: '|||aruba-clearpass-attribute-update'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      attribute_id:
        simple: ${HPEArubaClearpass.attributes.create.ID}
      data_type:
        simple: String
      entity_name:
        simple: GuestUser
      name:
        simple: ${RandomString}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 592.5,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "13":
    id: "13"
    taskid: bfe84785-5a9f-4346-816b-4dc2dd3f79dd
    type: condition
    task:
      id: bfe84785-5a9f-4346-816b-4dc2dd3f79dd
      version: -1
      name: Verify update attribute
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "14"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: ${HPEArubaClearpass.attributes.update.Name}
            iscontext: true
          right:
            value:
              simple: ${RandomString}
            iscontext: true
      - - operator: isEqualString
          left:
            value:
              simple: ${HPEArubaClearpass.attributes.update.ID}
            iscontext: true
          right:
            value:
              simple: ${HPEArubaClearpass.attributes.create.ID}
    view: |-
      {
        "position": {
          "x": 592.5,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "14":
    id: "14"
    taskid: 1152a779-1996-48a3-8cc2-39d9650a7b5d
    type: regular
    task:
      id: 1152a779-1996-48a3-8cc2-39d9650a7b5d
      version: -1
      name: Delete attribute
      description: Delete an attribute.
      script: '|||aruba-clearpass-attribute-delete'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      attribute_id:
        simple: ${HPEArubaClearpass.attributes.create.ID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 592.5,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "15":
    id: "15"
    taskid: d6e58732-8765-4bbb-832a-eea4bee7d08a
    type: regular
    task:
      id: d6e58732-8765-4bbb-832a-eea4bee7d08a
      version: -1
      name: Generate new attribute name
      description: Generates random string
      scriptName: GenerateRandomString
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      Digits:
        simple: "False"
      Length:
        simple: "7"
      Lowercase:
        simple: "True"
      Punctuation:
        simple: "False"
      Uppercase:
        simple: "True"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 592.5,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1610,
        "width": 922.5,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
fromversion: 6.0.0