id: CrowdStrike API - Test
version: -1
name: CrowdStrike API - Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: efec919b-07de-465d-828b-eaa84e89808e
    type: start
    task:
      id: efec919b-07de-465d-828b-eaa84e89808e
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: 6b49466d-c01f-4352-81b5-237a9feb477d
    type: regular
    task:
      id: 6b49466d-c01f-4352-81b5-237a9feb477d
      version: -1
      name: Query behaviors
      description: Run a CrowdStrike API query.
      script: '|||cs-api-request'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      endpoint:
        simple: /incidents/queries/behaviors/v1
      query_parameters:
        simple: '{"limit":1}'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: 848851a7-06f2-401a-8bf3-373ef409cb88
    type: condition
    task:
      id: 848851a7-06f2-401a-8bf3-373ef409cb88
      version: -1
      name: Verify Outputs
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "3"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: hasLength
          left:
            value:
              simple: CrowdStrike./incidents/queries/behaviors/v1
            iscontext: true
          right:
            value:
              simple: "1"
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: 9771813b-9f7f-43b2-8937-58096d3e81f9
    type: title
    task:
      id: 9771813b-9f7f-43b2-8937-58096d3e81f9
      version: -1
      name: Success
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: cc833971-43f4-4075-89cd-63675640988b
    type: regular
    task:
      id: cc833971-43f4-4075-89cd-63675640988b
      version: -1
      name: Delete Context
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 735,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
fromversion: 5.5.0
description: ''
