id: QRadar_v3 Search Polling
version: -1
name: QRadar_v3 Search Polling
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 3143855c-a6ac-409d-871d-29d2f09b478f
    type: start
    task:
      id: 3143855c-a6ac-409d-871d-29d2f09b478f
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: 03a00e3a-db12-460c-8e2d-f113544f88c6
    type: regular
    task:
      id: 03a00e3a-db12-460c-8e2d-f113544f88c6
      version: -1
      name: Create QRadar Search
      description: Create a new asynchronous Ariel search. Returns search ID. Search
        status and results can be polled by sending search ID to 'qradar-search-status-get'
        and 'qradar-search-results-get' commands. Accepts SELECT query expressions
        only.
      script: '|||qradar-search-create'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      query_expression:
        simple: ${inputs.query_expression}
      saved_search_id:
        simple: ${inputs.saved_search_id}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: a00291e2-decd-4b65-8694-083d9f0d1c55
    type: playbook
    task:
      id: a00291e2-decd-4b65-8694-083d9f0d1c55
      version: -1
      name: GenericPolling
      playbookName: GenericPolling
      type: playbook
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      AdditionalPollingCommandArgNames: {}
      AdditionalPollingCommandArgValues: {}
      Ids:
        simple: ${QRadar.Search.ID}
      Interval:
        simple: "1"
      PollingCommandArgName:
        simple: ids
      PollingCommandName:
        simple: qradar-search-status-get
      Timeout:
        simple: "10"
      dt:
        simple: QRadar.SearchStatus(val.Status != 'CANCELED' && val.Status != 'ERROR'
          && val.Status != 'COMPLETED').ID
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: 038a780e-3a78-4d2c-8d5b-0df33f8a657e
    type: regular
    task:
      id: 038a780e-3a78-4d2c-8d5b-0df33f8a657e
      version: -1
      name: Get QRadar Search Results
      description: Retrieves search results.
      script: '|||qradar-search-results-get'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      output_path:
        simple: ${inputs.output_path}
      range: {}
      search_id:
        simple: ${QRadar.Search.ID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: 0c56c66b-e937-439a-8882-581d48e91b03
    type: condition
    task:
      id: 0c56c66b-e937-439a-8882-581d48e91b03
      version: -1
      name: Check If Search Was Returned
      description: Checks if the given search have been completed before calling GenericPolling
        sub playbook.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "6"
      "yes":
      - "5"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: QRadar.Search.Result
            iscontext: true
    view: |-
      {
        "position": {
          "x": 265,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: 791f8eb2-83e1-448b-8879-bcf12192bb5e
    type: title
    task:
      id: 791f8eb2-83e1-448b-8879-bcf12192bb5e
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 910
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: e26d3db4-ee9e-4529-832d-15e9d668b73e
    type: regular
    task:
      id: e26d3db4-ee9e-4529-832d-15e9d668b73e
      version: -1
      name: Print Error Message
      description: Prints an error entry with a given message
      scriptName: PrintErrorEntry
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      message:
        simple: QRadar search was not completed.
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 940,
        "width": 810,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: query_expression
  value: {}
  required: false
  description: The AQL query to execute. Mutually exclusive with saved_search_id.
  playbookInputQuery:
- key: saved_search_id
  value: {}
  required: false
  description: Saved search ID to execute. Mutually exclusive with query_expression.
    Saved search ID is 'id' field returned by command 'qradar-saved-searches-list'.
  playbookInputQuery:
- key: output_path
  value: {}
  required: false
  description: Replaces the default context output path for the query result (QRadar.Search.Result).
    e.g. for output_path=QRadar.Correlations the result will be under the key 'QRadar.Correlations'
    in the context data.
  playbookInputQuery:
outputs: []
tests:
- test_Qradar
- test_Qradar_v2
- test_Qradar
- test playbook - QRadarCorrelations For V2
- QRadar_v3-test
- QRadar Indicator Hunting Test
- test playbook - QRadarCorrelations
fromversion: 6.0.0
description: This playbook runs a QRadar query and return its results to the context.
