id: FireEye Central Management - Test
fromversion: 5.5.0
version: -1
name: FireEye Central Management - Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 610cd349-9a8d-45b4-8554-fbf5d76e0bd7
    type: start
    task:
      id: 610cd349-9a8d-45b4-8554-fbf5d76e0bd7
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
  "1":
    id: "1"
    taskid: a61ffb02-9b12-47d4-8f27-6a465339a869
    type: regular
    task:
      id: a61ffb02-9b12-47d4-8f27-6a465339a869
      version: -1
      name: fireeye-cm-get-reports - ipsTopNAttack
      description: Returns reports on selected alerts.
      script: '|||fireeye-cm-get-reports'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      limit:
        simple: "100"
      report_type:
        simple: ipsTopNAttack
      timeout:
        simple: "90"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
  "2":
    id: "2"
    taskid: af52ea1f-2596-4eee-87eb-b6345d82a390
    type: regular
    task:
      id: af52ea1f-2596-4eee-87eb-b6345d82a390
      version: -1
      name: fireeye-cm-get-events
      description: Retrieve information about existing IPS NX events. An IPS enabled
        appliance is a prequisite to be able to retrieve IPS event data.
      script: '|||fireeye-cm-get-events'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
  "3":
    id: "3"
    taskid: 871d3541-f0bb-47d0-8e71-550efd7e8176
    type: regular
    task:
      id: 871d3541-f0bb-47d0-8e71-550efd7e8176
      version: -1
      name: fireeye-cm-get-reports alertDetailsReport
      description: Returns reports on selected alerts.
      script: '|||fireeye-cm-get-reports'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      alert_id:
        simple: "564"
      report_type:
        simple: alertDetailsReport
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
  "4":
    id: "4"
    taskid: 050df621-6425-431f-8e28-868c9c7cf0c0
    type: title
    task:
      id: 050df621-6425-431f-8e28-868c9c7cf0c0
      version: -1
      name: Done
      description: "done"
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 735,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []