id: XsoarPowershellTesting-Test
version: -1
name: XsoarPowershellTesting-Test
description: This playbook test basic powershell XSOAR server functionallity.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 41ea1302-cebe-49ed-88f6-90f1e0beb47e
    type: start
    task:
      id: 41ea1302-cebe-49ed-88f6-90f1e0beb47e
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 40,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 4ddb8aca-0ffc-430a-8ca5-96df31b5e1da
    type: regular
    task:
      id: 4ddb8aca-0ffc-430a-8ca5-96df31b5e1da
      version: -1
      name: Set integration context
      description: Set integration context.
      script: XsoarPowershellTesting|||pwsh-test-set-integration-context
      type: regular
      iscommand: true
      brand: XsoarPowershellTesting
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      value:
        complex:
          root: inputs.value
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: c3617d00-3122-48de-8cd2-404c07fe5ce6
    type: regular
    task:
      id: c3617d00-3122-48de-8cd2-404c07fe5ce6
      version: -1
      name: Get integration context
      description: Get integration context.
      script: XsoarPowershellTesting|||pwsh-test-get-integration-context
      type: regular
      iscommand: true
      brand: XsoarPowershellTesting
    nexttasks:
      '#none#':
      - "3"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 1e1b452b-b673-47c7-857a-00da8a98fe68
    type: condition
    task:
      id: 1e1b452b-b673-47c7-857a-00da8a98fe68
      version: -1
      name: Check integration context set/get value
      description: Check integration context setup succesfully and retrieve succesfully.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: XSOAR.IntegrationContext.Value
            iscontext: true
          right:
            value:
              simple: test
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 8d4a92c3-e3e3-4e1b-846d-9d2b5918dcc1
    type: title
    task:
      id: 8d4a92c3-e3e3-4e1b-846d-9d2b5918dcc1
      version: -1
      name: Finished succefully
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: cd96a984-ed3e-4750-8d30-403f6b1e7b28
    type: regular
    task:
      id: cd96a984-ed3e-4750-8d30-403f6b1e7b28
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 910,
        "width": 390,
        "x": 40,
        "y": 50
      }
    }
  }
inputs:
- key: value
  value:
    simple: test
  required: true
  description: Value to set in integration context
  playbookInputQuery: null
outputs: []
fromversion: 5.5.0
