description: Initiates a new endpoint script execution action using a provided script
  unique ID from the Cortex XDR script library.
id: Cortex XDR - Run script
inputs:
- description: 'A comma-separated list of endpoint IDs. '
  key: endpoint_ids
  playbookInputQuery:
  required: false
  value: {}
- description: Unique identifier of the script. Can be retrieved by running the xdr-get-scripts
    command.
  key: script_uid
  playbookInputQuery:
  required: false
  value: {}
- description: Dictionary contains the parameter name as key and its value for this
    execution as the value. For example, {"param1":"param1_value","param2":"param2_value"}
  key: parameters
  playbookInputQuery:
  required: false
  value: {}
- description: |-
    The timeout in seconds for this execution.
    (Default is: '600')
  key: timeout
  playbookInputQuery:
  required: false
  value: {}
name: Cortex XDR - Run script
outputs:
- contextPath: PaloAltoNetworksXDR.ScriptResult.results._return_value
  description: Value returned by the script in case the type is not a dictionary.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0a2f4a6b-3a8c-45f2-89ed-89eea47b1500
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: 0a2f4a6b-3a8c-45f2-89ed-89eea47b1500
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 60
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      endpoint_ids:
        complex:
          root: inputs.endpoint_ids
      parameters:
        complex:
          filters:
          - - left:
                iscontext: true
                value:
                  simple: inputs.parameters
              operator: isNotEmpty
          root: inputs.parameters
      script_uid:
        complex:
          root: inputs.script_uid
      timeout:
        complex:
          root: inputs.timeout
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Initiates a new endpoint script execution action using a script
        from the script library.
      id: af14806d-8b59-4b6d-8f03-21c2045832c6
      iscommand: true
      name: Execute Cortex XDR Script
      script: '|||xdr-run-script'
      type: regular
      version: -1
    taskid: af14806d-8b59-4b6d-8f03-21c2045832c6
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 190
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      action_id:
        complex:
          accessor: action_id
          root: PaloAltoNetworksXDR.ScriptRun
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 8708453a-a427-402e-80ae-c6c932c5358b
      iscommand: false
      name: Cortex XDR - Check Action Status
      playbookId: Cortex XDR - Check Action Status
      type: playbook
      version: -1
      description: ''
    taskid: 8708453a-a427-402e-80ae-c6c932c5358b
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 450,
          "y": 380
        }
      }
  "3":
    id: "3"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      action_id:
        complex:
          accessor: action_id
          root: PaloAltoNetworksXDR.ScriptRun
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Retrieve the results of a script execution action.
      id: 5487d7f4-691d-434e-828e-01190a697e56
      iscommand: true
      name: Get script execution results
      script: '|||xdr-get-script-execution-results'
      type: regular
      version: -1
    taskid: 5487d7f4-691d-434e-828e-01190a697e56
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 570
        }
      }
  "4":
    id: "4"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8de1f7d1-e21d-48a4-8760-0ed56299c77f
      iscommand: false
      name: Done
      type: title
      version: -1
      description: ''
    taskid: 8de1f7d1-e21d-48a4-8760-0ed56299c77f
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 730
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 735,
        "width": 380,
        "x": 450,
        "y": 60
      }
    }
  }
tests:
- No tests (auto formatted)
fromversion: 5.5.0
