id: Cortex XDR - Run script execute commands
version: -1
name: Cortex XDR - Run script execute commands
description: 'Use to Initiate a new script execution of shell commands. '
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: ac39719f-7adb-4e30-8b98-f5a5df25c325
    type: start
    task:
      id: ac39719f-7adb-4e30-8b98-f5a5df25c325
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: b4d2936d-31c5-4ea1-8587-9d7cb439245d
    type: regular
    task:
      id: b4d2936d-31c5-4ea1-8587-9d7cb439245d
      version: -1
      name: Run script execute commands
      description: Initiate a new endpoint script execution of shell commands.
      script: '|||xdr-run-script-execute-commands'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      commands:
        complex:
          root: inputs.commands
      endpoint_ids:
        complex:
          root: inputs.endpoint_ids
      timeout:
        complex:
          root: inputs.timeout
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 190
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: e780f6c6-9065-4730-809c-54ff6b2ff4eb
    type: playbook
    task:
      id: e780f6c6-9065-4730-809c-54ff6b2ff4eb
      version: -1
      name: Cortex XDR - Check Action Status
      playbookName: Cortex XDR - Check Action Status
      type: playbook
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      action_id:
        complex:
          root: PaloAltoNetworksXDR.ScriptRun
          accessor: action_id
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 450,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: e4e1bbc6-e612-4f5d-8dc8-65fd75f15766
    type: regular
    task:
      id: e4e1bbc6-e612-4f5d-8dc8-65fd75f15766
      version: -1
      name: Get script execution results
      description: Retrieve the results of a script execution action.
      script: '|||xdr-get-script-execution-results'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      action_id:
        complex:
          root: PaloAltoNetworksXDR.ScriptRun
          accessor: action_id
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 550
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: 07ef5958-2971-458a-8983-312970ae419b
    type: title
    task:
      id: 07ef5958-2971-458a-8983-312970ae419b
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 730
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 745,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
inputs:
- key: endpoint_ids
  value: {}
  required: false
  description: A comma-separated list of endpoint IDs.
  playbookInputQuery:
- key: commands
  value: {}
  required: false
  description: A comma-separated list of shell commands to execute.
  playbookInputQuery:
- key: timeout
  value: {}
  required: false
  description: |-
    The timeout in seconds for this execution.
    (Default is: '600')
  playbookInputQuery:
outputs: []
tests:
- No tests (auto formatted)
fromversion: 5.5.0
