description: |
  Initiates a new endpoint script execution to check if the file exists and retrieve the results.
id: Cortex XDR - check file existence
inputs:
- description: 'A comma-separated list of endpoint IDs. '
  key: endpoint_id
  playbookInputQuery:
  required: false
  value: {}
- description: Path of the file to check.
  key: file_path
  playbookInputQuery:
  required: false
  value: {}
- description: |-
    The timeout in seconds for this execution.
    (Default is: '600')
  key: timeout
  playbookInputQuery:
  required: false
  value: {}
name: Cortex XDR - check file existence
outputs:
- contextPath: PaloAltoNetworksXDR.ScriptResult.results._return_value
  description: Value returned by the script in case the type is not a dictionary.
  type: boolean
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 2e8588ea-e14e-4a63-87e5-35bcb394c162
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: 2e8588ea-e14e-4a63-87e5-35bcb394c162
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      endpoint_ids:
        complex:
          root: inputs.endpoint_id
      file_path:
        complex:
          root: inputs.file_path
      timeout:
        complex:
          root: inputs.timeout
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Initiates a new endpoint script execution to check if the file exists.
      id: af2ebc62-afc0-4284-8a90-aa07d85df504
      iscommand: true
      name: Run script file exists
      script: '|||xdr-run-script-file-exists'
      type: regular
      version: -1
    taskid: af2ebc62-afc0-4284-8a90-aa07d85df504
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 200
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      action_id:
        complex:
          accessor: action_id
          root: PaloAltoNetworksXDR.ScriptRun
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: eaf294e5-bbf8-4591-89f2-e8a40efeb086
      iscommand: false
      name: Cortex XDR - Check Action Status
      playbookId: Cortex XDR - Check Action Status
      type: playbook
      version: -1
      description: ''
    taskid: eaf294e5-bbf8-4591-89f2-e8a40efeb086
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 450,
          "y": 380
        }
      }
  "3":
    id: "3"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      action_id:
        complex:
          accessor: action_id
          root: PaloAltoNetworksXDR.ScriptRun
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Retrieve the results of a script execution action.
      id: 8034abda-d134-4b58-821b-54de3c774b29
      iscommand: true
      name: Get script execution results
      script: '|||xdr-get-script-execution-results'
      type: regular
      version: -1
    taskid: 8034abda-d134-4b58-821b-54de3c774b29
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 560
        }
      }
  "4":
    id: "4"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 91e2d310-e3ac-4781-8866-d2a422edc8b6
      iscommand: false
      name: Done
      type: title
      version: -1
      description: ''
    taskid: 91e2d310-e3ac-4781-8866-d2a422edc8b6
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 730
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 745,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
tests:
- No tests (auto formatted)
fromversion: 5.5.0
