description: 'Use to Initiate a new script execution of shell commands. '
id: Cortex XDR - execute commands
inputs:
- description: A comma-separated list of endpoint IDs.
  key: endpoint_ids
  playbookInputQuery:
  required: false
  value: {}
- description: A comma-separated list of shell commands to execute.
  key: commands
  playbookInputQuery:
  required: false
  value: {}
- description: |-
    The timeout in seconds for this execution.
    (Default is: '600')
  key: timeout
  playbookInputQuery:
  required: false
  value: {}
name: Cortex XDR - execute commands
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: ac39719f-7adb-4e30-8b98-f5a5df25c325
      iscommand: false
      name: ""
      version: -1
      description: ''
    taskid: ac39719f-7adb-4e30-8b98-f5a5df25c325
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      commands:
        complex:
          root: inputs.commands
      endpoint_ids:
        complex:
          root: inputs.endpoint_ids
      timeout:
        complex:
          root: inputs.timeout
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Initiate a new endpoint script execution of shell commands.
      id: b4d2936d-31c5-4ea1-8587-9d7cb439245d
      iscommand: true
      name: Run script execute commands
      script: '|||xdr-run-script-execute-commands'
      type: regular
      version: -1
    taskid: b4d2936d-31c5-4ea1-8587-9d7cb439245d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 190
        }
      }
  "2":
    id: "2"
    ignoreworker: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      action_id:
        complex:
          accessor: action_id
          root: PaloAltoNetworksXDR.ScriptRun
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: e780f6c6-9065-4730-809c-54ff6b2ff4eb
      iscommand: false
      name: Cortex XDR - Check Action Status
      playbookId: Cortex XDR - Check Action Status
      type: playbook
      version: -1
      description: ''
    taskid: e780f6c6-9065-4730-809c-54ff6b2ff4eb
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 450,
          "y": 370
        }
      }
  "3":
    id: "3"
    ignoreworker: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      action_id:
        complex:
          accessor: action_id
          root: PaloAltoNetworksXDR.ScriptRun
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Retrieve the results of a script execution action.
      id: e4e1bbc6-e612-4f5d-8dc8-65fd75f15766
      iscommand: true
      name: Get script execution results
      script: '|||xdr-get-script-execution-results'
      type: regular
      version: -1
    taskid: e4e1bbc6-e612-4f5d-8dc8-65fd75f15766
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 550
        }
      }
  "4":
    id: "4"
    ignoreworker: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 07ef5958-2971-458a-8983-312970ae419b
      iscommand: false
      name: Done
      type: title
      version: -1
      description: ''
    taskid: 07ef5958-2971-458a-8983-312970ae419b
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 730
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 745,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
tests:
- No tests (auto formatted)
fromversion: 5.5.0
