id: Azure SecurityCenter - Test self deployed
version: -1
name: Azure SecurityCenter - Test self deployed
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: e17315f4-79eb-4af2-a0ee-6bca915cb154
    type: start
    task:
      id: e17315f4-79eb-4af2-a0ee-6bca915cb154
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
  "1":
    id: "1"
    taskid: 8e42791b-5fa5-4456-83bf-aefb711ceafd
    type: regular
    task:
      id: 8e42791b-5fa5-4456-83bf-aefb711ceafd
      version: -1
      name: set playbook to Azure SecurityCenter - Test
      description: set playbook for current incident to Azure SecurityCenter - Test
      script: Builtin|||setPlaybook
      type: regular
      iscommand: true
      brand: Builtin
    scriptarguments:
      incidentId:
        simple: ${incident.id}
      name:
        simple: Azure SecurityCenter - Test
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 230
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 275,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
fromversion: 5.0.0
